-- AlterTable
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "useProductCountLimit" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "minProductsPerSet" INTEGER;
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "maxProductsPerSet" INTEGER;
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "conceptCount" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "visualizationCount" INTEGER NOT NULL DEFAULT 1;
