import { ConfigService } from '@nestjs/config';
import { Queue } from 'bullmq';
import { PrismaService } from '../prisma/prisma.service';
import { AgentRunJobData } from './agent-run.queue';
export declare class AgentRunService {
    private readonly prisma;
    private readonly config;
    private readonly queue;
    constructor(prisma: PrismaService, config: ConfigService, queue: Queue<AgentRunJobData>);
    private assertEnabled;
    start(requestId: string, options?: {
        debug?: boolean;
        aiStyle?: 'catalog' | 'creative';
    }): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        chosenIdeaTitle: string | null;
        status: import("@prisma/client").$Enums.AgentRunStatus;
        updatedAt: Date;
        requestId: string;
        startedAt: Date | null;
        finishedAt: Date | null;
        route: import("@prisma/client").$Enums.AgentRoute | null;
        currentStep: string | null;
        routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
        ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
        criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
        promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
        directProducts: import("@prisma/client/runtime/library").JsonValue | null;
        conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
        imageResultUrl: string | null;
        debugEnabled: boolean;
        debugLog: import("@prisma/client/runtime/library").JsonValue | null;
    } | null>;
    selectConcept(requestId: string, chosenIdeaTitle: string): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        chosenIdeaTitle: string | null;
        status: import("@prisma/client").$Enums.AgentRunStatus;
        updatedAt: Date;
        requestId: string;
        startedAt: Date | null;
        finishedAt: Date | null;
        route: import("@prisma/client").$Enums.AgentRoute | null;
        currentStep: string | null;
        routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
        ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
        criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
        promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
        directProducts: import("@prisma/client/runtime/library").JsonValue | null;
        conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
        imageResultUrl: string | null;
        debugEnabled: boolean;
        debugLog: import("@prisma/client/runtime/library").JsonValue | null;
    } | null>;
    continue(requestId: string, body: {
        chosenIdeaTitle?: string;
        productIds?: string[];
    }): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        chosenIdeaTitle: string | null;
        status: import("@prisma/client").$Enums.AgentRunStatus;
        updatedAt: Date;
        requestId: string;
        startedAt: Date | null;
        finishedAt: Date | null;
        route: import("@prisma/client").$Enums.AgentRoute | null;
        currentStep: string | null;
        routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
        ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
        criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
        promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
        directProducts: import("@prisma/client/runtime/library").JsonValue | null;
        conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
        imageResultUrl: string | null;
        debugEnabled: boolean;
        debugLog: import("@prisma/client/runtime/library").JsonValue | null;
    } | null>;
    retry(requestId: string, options?: {
        aiStyle?: 'catalog' | 'creative';
    }): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        chosenIdeaTitle: string | null;
        status: import("@prisma/client").$Enums.AgentRunStatus;
        updatedAt: Date;
        requestId: string;
        startedAt: Date | null;
        finishedAt: Date | null;
        route: import("@prisma/client").$Enums.AgentRoute | null;
        currentStep: string | null;
        routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
        ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
        criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
        promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
        directProducts: import("@prisma/client/runtime/library").JsonValue | null;
        conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
        imageResultUrl: string | null;
        debugEnabled: boolean;
        debugLog: import("@prisma/client/runtime/library").JsonValue | null;
    } | null>;
    getByRequestId(requestId: string): Promise<{
        error: string | null;
        id: string;
        createdAt: Date;
        chosenIdeaTitle: string | null;
        status: import("@prisma/client").$Enums.AgentRunStatus;
        updatedAt: Date;
        requestId: string;
        startedAt: Date | null;
        finishedAt: Date | null;
        route: import("@prisma/client").$Enums.AgentRoute | null;
        currentStep: string | null;
        routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
        ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
        criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
        promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
        directProducts: import("@prisma/client/runtime/library").JsonValue | null;
        conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
        imageResultUrl: string | null;
        debugEnabled: boolean;
        debugLog: import("@prisma/client/runtime/library").JsonValue | null;
    } | null>;
}
