import { PrismaService } from '../prisma/prisma.service';
import { CreateRequestDto } from './dto/create-request.dto';
import { UpdateRequestDto } from './dto/update-request.dto';
import { LlmBriefService } from '../providers/llm/llm-brief.service';
export declare class RequestsService {
    private readonly prisma;
    private readonly llmBrief;
    constructor(prisma: PrismaService, llmBrief: LlmBriefService);
    create(dto: CreateRequestDto): Promise<{
        agentRun: {
            error: string | null;
            id: string;
            createdAt: Date;
            chosenIdeaTitle: string | null;
            status: import("@prisma/client").$Enums.AgentRunStatus;
            updatedAt: Date;
            requestId: string;
            startedAt: Date | null;
            finishedAt: Date | null;
            route: import("@prisma/client").$Enums.AgentRoute | null;
            currentStep: string | null;
            routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
            ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
            criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
            promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
            directProducts: import("@prisma/client/runtime/library").JsonValue | null;
            conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imageResultUrl: string | null;
            debugEnabled: boolean;
            debugLog: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        generation: ({
            variants: {
                id: string;
                createdAt: Date;
                imagePrompt: string | null;
                generationId: string;
                imageUrl: string;
                refinementBrief: string | null;
                sortOrder: number;
            }[];
        } & {
            id: string;
            createdAt: Date;
            status: import("@prisma/client").$Enums.GenerationStatus;
            requestId: string;
            inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
            llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imagePrompt: string | null;
            negativePrompt: string | null;
            resultImageUrl: string | null;
            conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        }) | null;
        items: ({
            product: {
                id: string;
                slug: string;
                name: string;
                category: string;
                subcategory: string | null;
                description: string | null;
                sourceId: string | null;
                externalId: string | null;
                price: number | null;
                currency: string;
                stockAvailable: number;
                colors: import("@prisma/client/runtime/library").JsonValue;
                sourceUrl: string | null;
                silhouetteImageUrl: string;
                catalogImageUrl: string | null;
                createdAt: Date;
            };
        } & {
            id: string;
            productId: string;
            requestId: string;
        })[];
        assets: {
            id: string;
            createdAt: Date;
            url: string;
            type: import("@prisma/client").$Enums.AssetType;
            requestId: string;
        }[];
    } & {
        id: string;
        category: string;
        colors: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        title: string;
        userPrompt: string;
        budgetMin: number | null;
        budgetMax: number | null;
        quantity: number | null;
        allowedItems: import("@prisma/client/runtime/library").JsonValue;
        forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
        setItemCount: number | null;
        useProductCountLimit: boolean;
        minProductsPerSet: number | null;
        maxProductsPerSet: number | null;
        conceptCount: number;
        visualizationCount: number;
        notes: string | null;
        blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
        blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
        status: import("@prisma/client").$Enums.RequestStatus;
        generationCount: number;
        generationLockedAt: Date | null;
        updatedAt: Date;
    }>;
    findOne(id: string): Promise<({
        agentRun: {
            error: string | null;
            id: string;
            createdAt: Date;
            chosenIdeaTitle: string | null;
            status: import("@prisma/client").$Enums.AgentRunStatus;
            updatedAt: Date;
            requestId: string;
            startedAt: Date | null;
            finishedAt: Date | null;
            route: import("@prisma/client").$Enums.AgentRoute | null;
            currentStep: string | null;
            routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
            ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
            criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
            promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
            directProducts: import("@prisma/client/runtime/library").JsonValue | null;
            conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imageResultUrl: string | null;
            debugEnabled: boolean;
            debugLog: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        generation: ({
            variants: {
                id: string;
                createdAt: Date;
                imagePrompt: string | null;
                generationId: string;
                imageUrl: string;
                refinementBrief: string | null;
                sortOrder: number;
            }[];
        } & {
            id: string;
            createdAt: Date;
            status: import("@prisma/client").$Enums.GenerationStatus;
            requestId: string;
            inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
            llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imagePrompt: string | null;
            negativePrompt: string | null;
            resultImageUrl: string | null;
            conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        }) | null;
        items: ({
            product: {
                id: string;
                slug: string;
                name: string;
                category: string;
                subcategory: string | null;
                description: string | null;
                sourceId: string | null;
                externalId: string | null;
                price: number | null;
                currency: string;
                stockAvailable: number;
                colors: import("@prisma/client/runtime/library").JsonValue;
                sourceUrl: string | null;
                silhouetteImageUrl: string;
                catalogImageUrl: string | null;
                createdAt: Date;
            };
        } & {
            id: string;
            productId: string;
            requestId: string;
        })[];
        assets: {
            id: string;
            createdAt: Date;
            url: string;
            type: import("@prisma/client").$Enums.AssetType;
            requestId: string;
        }[];
    } & {
        id: string;
        category: string;
        colors: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        title: string;
        userPrompt: string;
        budgetMin: number | null;
        budgetMax: number | null;
        quantity: number | null;
        allowedItems: import("@prisma/client/runtime/library").JsonValue;
        forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
        setItemCount: number | null;
        useProductCountLimit: boolean;
        minProductsPerSet: number | null;
        maxProductsPerSet: number | null;
        conceptCount: number;
        visualizationCount: number;
        notes: string | null;
        blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
        blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
        status: import("@prisma/client").$Enums.RequestStatus;
        generationCount: number;
        generationLockedAt: Date | null;
        updatedAt: Date;
    }) | {
        generation: {
            conceptResults: import("../generation/concept-result.util").ConceptResultsMap;
            variants: {
                id: string;
                createdAt: Date;
                imagePrompt: string | null;
                generationId: string;
                imageUrl: string;
                refinementBrief: string | null;
                sortOrder: number;
            }[];
            id: string;
            createdAt: Date;
            status: import("@prisma/client").$Enums.GenerationStatus;
            requestId: string;
            inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
            llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imagePrompt: string | null;
            negativePrompt: string | null;
            resultImageUrl: string | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        };
        agentRun: {
            error: string | null;
            id: string;
            createdAt: Date;
            chosenIdeaTitle: string | null;
            status: import("@prisma/client").$Enums.AgentRunStatus;
            updatedAt: Date;
            requestId: string;
            startedAt: Date | null;
            finishedAt: Date | null;
            route: import("@prisma/client").$Enums.AgentRoute | null;
            currentStep: string | null;
            routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
            ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
            criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
            promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
            directProducts: import("@prisma/client/runtime/library").JsonValue | null;
            conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imageResultUrl: string | null;
            debugEnabled: boolean;
            debugLog: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        items: ({
            product: {
                id: string;
                slug: string;
                name: string;
                category: string;
                subcategory: string | null;
                description: string | null;
                sourceId: string | null;
                externalId: string | null;
                price: number | null;
                currency: string;
                stockAvailable: number;
                colors: import("@prisma/client/runtime/library").JsonValue;
                sourceUrl: string | null;
                silhouetteImageUrl: string;
                catalogImageUrl: string | null;
                createdAt: Date;
            };
        } & {
            id: string;
            productId: string;
            requestId: string;
        })[];
        assets: {
            id: string;
            createdAt: Date;
            url: string;
            type: import("@prisma/client").$Enums.AssetType;
            requestId: string;
        }[];
        id: string;
        category: string;
        colors: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        title: string;
        userPrompt: string;
        budgetMin: number | null;
        budgetMax: number | null;
        quantity: number | null;
        allowedItems: import("@prisma/client/runtime/library").JsonValue;
        forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
        setItemCount: number | null;
        useProductCountLimit: boolean;
        minProductsPerSet: number | null;
        maxProductsPerSet: number | null;
        conceptCount: number;
        visualizationCount: number;
        notes: string | null;
        blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
        blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
        status: import("@prisma/client").$Enums.RequestStatus;
        generationCount: number;
        generationLockedAt: Date | null;
        updatedAt: Date;
    }>;
    update(id: string, dto: UpdateRequestDto): Promise<{
        agentRun: {
            error: string | null;
            id: string;
            createdAt: Date;
            chosenIdeaTitle: string | null;
            status: import("@prisma/client").$Enums.AgentRunStatus;
            updatedAt: Date;
            requestId: string;
            startedAt: Date | null;
            finishedAt: Date | null;
            route: import("@prisma/client").$Enums.AgentRoute | null;
            currentStep: string | null;
            routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
            ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
            criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
            promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
            directProducts: import("@prisma/client/runtime/library").JsonValue | null;
            conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imageResultUrl: string | null;
            debugEnabled: boolean;
            debugLog: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        generation: ({
            variants: {
                id: string;
                createdAt: Date;
                imagePrompt: string | null;
                generationId: string;
                imageUrl: string;
                refinementBrief: string | null;
                sortOrder: number;
            }[];
        } & {
            id: string;
            createdAt: Date;
            status: import("@prisma/client").$Enums.GenerationStatus;
            requestId: string;
            inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
            llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imagePrompt: string | null;
            negativePrompt: string | null;
            resultImageUrl: string | null;
            conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        }) | null;
        items: ({
            product: {
                id: string;
                slug: string;
                name: string;
                category: string;
                subcategory: string | null;
                description: string | null;
                sourceId: string | null;
                externalId: string | null;
                price: number | null;
                currency: string;
                stockAvailable: number;
                colors: import("@prisma/client/runtime/library").JsonValue;
                sourceUrl: string | null;
                silhouetteImageUrl: string;
                catalogImageUrl: string | null;
                createdAt: Date;
            };
        } & {
            id: string;
            productId: string;
            requestId: string;
        })[];
        assets: {
            id: string;
            createdAt: Date;
            url: string;
            type: import("@prisma/client").$Enums.AssetType;
            requestId: string;
        }[];
    } & {
        id: string;
        category: string;
        colors: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        title: string;
        userPrompt: string;
        budgetMin: number | null;
        budgetMax: number | null;
        quantity: number | null;
        allowedItems: import("@prisma/client/runtime/library").JsonValue;
        forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
        setItemCount: number | null;
        useProductCountLimit: boolean;
        minProductsPerSet: number | null;
        maxProductsPerSet: number | null;
        conceptCount: number;
        visualizationCount: number;
        notes: string | null;
        blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
        blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
        status: import("@prisma/client").$Enums.RequestStatus;
        generationCount: number;
        generationLockedAt: Date | null;
        updatedAt: Date;
    }>;
    submit(id: string): Promise<{
        agentRun: {
            error: string | null;
            id: string;
            createdAt: Date;
            chosenIdeaTitle: string | null;
            status: import("@prisma/client").$Enums.AgentRunStatus;
            updatedAt: Date;
            requestId: string;
            startedAt: Date | null;
            finishedAt: Date | null;
            route: import("@prisma/client").$Enums.AgentRoute | null;
            currentStep: string | null;
            routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
            ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
            criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
            promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
            directProducts: import("@prisma/client/runtime/library").JsonValue | null;
            conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imageResultUrl: string | null;
            debugEnabled: boolean;
            debugLog: import("@prisma/client/runtime/library").JsonValue | null;
        } | null;
        generation: ({
            variants: {
                id: string;
                createdAt: Date;
                imagePrompt: string | null;
                generationId: string;
                imageUrl: string;
                refinementBrief: string | null;
                sortOrder: number;
            }[];
        } & {
            id: string;
            createdAt: Date;
            status: import("@prisma/client").$Enums.GenerationStatus;
            requestId: string;
            inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
            llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
            imagePrompt: string | null;
            negativePrompt: string | null;
            resultImageUrl: string | null;
            conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
            startedAt: Date | null;
            finishedAt: Date | null;
        }) | null;
        items: ({
            product: {
                id: string;
                slug: string;
                name: string;
                category: string;
                subcategory: string | null;
                description: string | null;
                sourceId: string | null;
                externalId: string | null;
                price: number | null;
                currency: string;
                stockAvailable: number;
                colors: import("@prisma/client/runtime/library").JsonValue;
                sourceUrl: string | null;
                silhouetteImageUrl: string;
                catalogImageUrl: string | null;
                createdAt: Date;
            };
        } & {
            id: string;
            productId: string;
            requestId: string;
        })[];
        assets: {
            id: string;
            createdAt: Date;
            url: string;
            type: import("@prisma/client").$Enums.AssetType;
            requestId: string;
        }[];
    } & {
        id: string;
        category: string;
        colors: import("@prisma/client/runtime/library").JsonValue;
        createdAt: Date;
        title: string;
        userPrompt: string;
        budgetMin: number | null;
        budgetMax: number | null;
        quantity: number | null;
        allowedItems: import("@prisma/client/runtime/library").JsonValue;
        forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
        setItemCount: number | null;
        useProductCountLimit: boolean;
        minProductsPerSet: number | null;
        maxProductsPerSet: number | null;
        conceptCount: number;
        visualizationCount: number;
        notes: string | null;
        blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
        blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
        status: import("@prisma/client").$Enums.RequestStatus;
        generationCount: number;
        generationLockedAt: Date | null;
        updatedAt: Date;
    }>;
    parseBrief(userPrompt: string): Promise<import("./parse-brief.util").ParsedBriefResult & {
        source: string;
    }>;
    extractParameters(id: string): Promise<{
        request: ({
            agentRun: {
                error: string | null;
                id: string;
                createdAt: Date;
                chosenIdeaTitle: string | null;
                status: import("@prisma/client").$Enums.AgentRunStatus;
                updatedAt: Date;
                requestId: string;
                startedAt: Date | null;
                finishedAt: Date | null;
                route: import("@prisma/client").$Enums.AgentRoute | null;
                currentStep: string | null;
                routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
                ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
                criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
                promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
                directProducts: import("@prisma/client/runtime/library").JsonValue | null;
                conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imageResultUrl: string | null;
                debugEnabled: boolean;
                debugLog: import("@prisma/client/runtime/library").JsonValue | null;
            } | null;
            generation: ({
                variants: {
                    id: string;
                    createdAt: Date;
                    imagePrompt: string | null;
                    generationId: string;
                    imageUrl: string;
                    refinementBrief: string | null;
                    sortOrder: number;
                }[];
            } & {
                id: string;
                createdAt: Date;
                status: import("@prisma/client").$Enums.GenerationStatus;
                requestId: string;
                inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
                llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imagePrompt: string | null;
                negativePrompt: string | null;
                resultImageUrl: string | null;
                conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
                startedAt: Date | null;
                finishedAt: Date | null;
            }) | null;
            items: ({
                product: {
                    id: string;
                    slug: string;
                    name: string;
                    category: string;
                    subcategory: string | null;
                    description: string | null;
                    sourceId: string | null;
                    externalId: string | null;
                    price: number | null;
                    currency: string;
                    stockAvailable: number;
                    colors: import("@prisma/client/runtime/library").JsonValue;
                    sourceUrl: string | null;
                    silhouetteImageUrl: string;
                    catalogImageUrl: string | null;
                    createdAt: Date;
                };
            } & {
                id: string;
                productId: string;
                requestId: string;
            })[];
            assets: {
                id: string;
                createdAt: Date;
                url: string;
                type: import("@prisma/client").$Enums.AssetType;
                requestId: string;
            }[];
        } & {
            id: string;
            category: string;
            colors: import("@prisma/client/runtime/library").JsonValue;
            createdAt: Date;
            title: string;
            userPrompt: string;
            budgetMin: number | null;
            budgetMax: number | null;
            quantity: number | null;
            allowedItems: import("@prisma/client/runtime/library").JsonValue;
            forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
            setItemCount: number | null;
            useProductCountLimit: boolean;
            minProductsPerSet: number | null;
            maxProductsPerSet: number | null;
            conceptCount: number;
            visualizationCount: number;
            notes: string | null;
            blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
            blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
            status: import("@prisma/client").$Enums.RequestStatus;
            generationCount: number;
            generationLockedAt: Date | null;
            updatedAt: Date;
        }) | {
            generation: {
                conceptResults: import("../generation/concept-result.util").ConceptResultsMap;
                variants: {
                    id: string;
                    createdAt: Date;
                    imagePrompt: string | null;
                    generationId: string;
                    imageUrl: string;
                    refinementBrief: string | null;
                    sortOrder: number;
                }[];
                id: string;
                createdAt: Date;
                status: import("@prisma/client").$Enums.GenerationStatus;
                requestId: string;
                inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
                llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imagePrompt: string | null;
                negativePrompt: string | null;
                resultImageUrl: string | null;
                startedAt: Date | null;
                finishedAt: Date | null;
            };
            agentRun: {
                error: string | null;
                id: string;
                createdAt: Date;
                chosenIdeaTitle: string | null;
                status: import("@prisma/client").$Enums.AgentRunStatus;
                updatedAt: Date;
                requestId: string;
                startedAt: Date | null;
                finishedAt: Date | null;
                route: import("@prisma/client").$Enums.AgentRoute | null;
                currentStep: string | null;
                routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
                ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
                criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
                promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
                directProducts: import("@prisma/client/runtime/library").JsonValue | null;
                conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imageResultUrl: string | null;
                debugEnabled: boolean;
                debugLog: import("@prisma/client/runtime/library").JsonValue | null;
            } | null;
            items: ({
                product: {
                    id: string;
                    slug: string;
                    name: string;
                    category: string;
                    subcategory: string | null;
                    description: string | null;
                    sourceId: string | null;
                    externalId: string | null;
                    price: number | null;
                    currency: string;
                    stockAvailable: number;
                    colors: import("@prisma/client/runtime/library").JsonValue;
                    sourceUrl: string | null;
                    silhouetteImageUrl: string;
                    catalogImageUrl: string | null;
                    createdAt: Date;
                };
            } & {
                id: string;
                productId: string;
                requestId: string;
            })[];
            assets: {
                id: string;
                createdAt: Date;
                url: string;
                type: import("@prisma/client").$Enums.AssetType;
                requestId: string;
            }[];
            id: string;
            category: string;
            colors: import("@prisma/client/runtime/library").JsonValue;
            createdAt: Date;
            title: string;
            userPrompt: string;
            budgetMin: number | null;
            budgetMax: number | null;
            quantity: number | null;
            allowedItems: import("@prisma/client/runtime/library").JsonValue;
            forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
            setItemCount: number | null;
            useProductCountLimit: boolean;
            minProductsPerSet: number | null;
            maxProductsPerSet: number | null;
            conceptCount: number;
            visualizationCount: number;
            notes: string | null;
            blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
            blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
            status: import("@prisma/client").$Enums.RequestStatus;
            generationCount: number;
            generationLockedAt: Date | null;
            updatedAt: Date;
        };
        parameters: import("./analyze-brief.util").BriefParameters;
        parsed: import("./parse-brief.util").ParsedBriefResult & {
            source: string;
        };
    }>;
    suggestProducts(id: string): Promise<{
        request: ({
            agentRun: {
                error: string | null;
                id: string;
                createdAt: Date;
                chosenIdeaTitle: string | null;
                status: import("@prisma/client").$Enums.AgentRunStatus;
                updatedAt: Date;
                requestId: string;
                startedAt: Date | null;
                finishedAt: Date | null;
                route: import("@prisma/client").$Enums.AgentRoute | null;
                currentStep: string | null;
                routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
                ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
                criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
                promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
                directProducts: import("@prisma/client/runtime/library").JsonValue | null;
                conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imageResultUrl: string | null;
                debugEnabled: boolean;
                debugLog: import("@prisma/client/runtime/library").JsonValue | null;
            } | null;
            generation: ({
                variants: {
                    id: string;
                    createdAt: Date;
                    imagePrompt: string | null;
                    generationId: string;
                    imageUrl: string;
                    refinementBrief: string | null;
                    sortOrder: number;
                }[];
            } & {
                id: string;
                createdAt: Date;
                status: import("@prisma/client").$Enums.GenerationStatus;
                requestId: string;
                inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
                llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imagePrompt: string | null;
                negativePrompt: string | null;
                resultImageUrl: string | null;
                conceptResults: import("@prisma/client/runtime/library").JsonValue | null;
                startedAt: Date | null;
                finishedAt: Date | null;
            }) | null;
            items: ({
                product: {
                    id: string;
                    slug: string;
                    name: string;
                    category: string;
                    subcategory: string | null;
                    description: string | null;
                    sourceId: string | null;
                    externalId: string | null;
                    price: number | null;
                    currency: string;
                    stockAvailable: number;
                    colors: import("@prisma/client/runtime/library").JsonValue;
                    sourceUrl: string | null;
                    silhouetteImageUrl: string;
                    catalogImageUrl: string | null;
                    createdAt: Date;
                };
            } & {
                id: string;
                productId: string;
                requestId: string;
            })[];
            assets: {
                id: string;
                createdAt: Date;
                url: string;
                type: import("@prisma/client").$Enums.AssetType;
                requestId: string;
            }[];
        } & {
            id: string;
            category: string;
            colors: import("@prisma/client/runtime/library").JsonValue;
            createdAt: Date;
            title: string;
            userPrompt: string;
            budgetMin: number | null;
            budgetMax: number | null;
            quantity: number | null;
            allowedItems: import("@prisma/client/runtime/library").JsonValue;
            forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
            setItemCount: number | null;
            useProductCountLimit: boolean;
            minProductsPerSet: number | null;
            maxProductsPerSet: number | null;
            conceptCount: number;
            visualizationCount: number;
            notes: string | null;
            blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
            blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
            status: import("@prisma/client").$Enums.RequestStatus;
            generationCount: number;
            generationLockedAt: Date | null;
            updatedAt: Date;
        }) | {
            generation: {
                conceptResults: import("../generation/concept-result.util").ConceptResultsMap;
                variants: {
                    id: string;
                    createdAt: Date;
                    imagePrompt: string | null;
                    generationId: string;
                    imageUrl: string;
                    refinementBrief: string | null;
                    sortOrder: number;
                }[];
                id: string;
                createdAt: Date;
                status: import("@prisma/client").$Enums.GenerationStatus;
                requestId: string;
                inputSnapshot: import("@prisma/client/runtime/library").JsonValue;
                llmOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imagePrompt: string | null;
                negativePrompt: string | null;
                resultImageUrl: string | null;
                startedAt: Date | null;
                finishedAt: Date | null;
            };
            agentRun: {
                error: string | null;
                id: string;
                createdAt: Date;
                chosenIdeaTitle: string | null;
                status: import("@prisma/client").$Enums.AgentRunStatus;
                updatedAt: Date;
                requestId: string;
                startedAt: Date | null;
                finishedAt: Date | null;
                route: import("@prisma/client").$Enums.AgentRoute | null;
                currentStep: string | null;
                routerOutput: import("@prisma/client/runtime/library").JsonValue | null;
                ideatorOutput: import("@prisma/client/runtime/library").JsonValue | null;
                criticOutput: import("@prisma/client/runtime/library").JsonValue | null;
                promptOutput: import("@prisma/client/runtime/library").JsonValue | null;
                directProducts: import("@prisma/client/runtime/library").JsonValue | null;
                conceptsOutput: import("@prisma/client/runtime/library").JsonValue | null;
                imageResultUrl: string | null;
                debugEnabled: boolean;
                debugLog: import("@prisma/client/runtime/library").JsonValue | null;
            } | null;
            items: ({
                product: {
                    id: string;
                    slug: string;
                    name: string;
                    category: string;
                    subcategory: string | null;
                    description: string | null;
                    sourceId: string | null;
                    externalId: string | null;
                    price: number | null;
                    currency: string;
                    stockAvailable: number;
                    colors: import("@prisma/client/runtime/library").JsonValue;
                    sourceUrl: string | null;
                    silhouetteImageUrl: string;
                    catalogImageUrl: string | null;
                    createdAt: Date;
                };
            } & {
                id: string;
                productId: string;
                requestId: string;
            })[];
            assets: {
                id: string;
                createdAt: Date;
                url: string;
                type: import("@prisma/client").$Enums.AssetType;
                requestId: string;
            }[];
            id: string;
            category: string;
            colors: import("@prisma/client/runtime/library").JsonValue;
            createdAt: Date;
            title: string;
            userPrompt: string;
            budgetMin: number | null;
            budgetMax: number | null;
            quantity: number | null;
            allowedItems: import("@prisma/client/runtime/library").JsonValue;
            forbiddenItems: import("@prisma/client/runtime/library").JsonValue;
            setItemCount: number | null;
            useProductCountLimit: boolean;
            minProductsPerSet: number | null;
            maxProductsPerSet: number | null;
            conceptCount: number;
            visualizationCount: number;
            notes: string | null;
            blacklistedProductIds: import("@prisma/client/runtime/library").JsonValue;
            blacklistedSupplierIds: import("@prisma/client/runtime/library").JsonValue;
            status: import("@prisma/client").$Enums.RequestStatus;
            generationCount: number;
            generationLockedAt: Date | null;
            updatedAt: Date;
        };
        suggestion: {
            productIds: string[];
            productNames: string[];
            products: {
                id: string;
                name: string;
                category: string;
                price: number | null | undefined;
                stockAvailable: number | undefined;
                colors: string[];
            }[];
            setPriceRub: number;
            composition: string;
            style: string;
            image_prompt: string;
            llmProvider: string;
            modelUsed: string | null;
            desiredItemCount: number | undefined;
            usedFallback: boolean;
            catalogStats: {
                totalInDb: number;
                afterFilters: number;
                sentToLlm: number;
            };
        };
    }>;
    suggestProductAdd(id: string, body: {
        currentProductIds: string[];
        hint?: string;
    }): Promise<{
        suggestions: {
            product: {
                id: string;
                name: string;
                category: string;
                price: number | null | undefined;
                stockAvailable: number | undefined;
                colors: string[];
                catalogImageUrl: string | null | undefined;
                silhouetteImageUrl: string;
                sourceUrl: string | null;
            };
            reason: string;
            targetColor: string | undefined;
        }[];
        usedFallback: boolean;
    }>;
}
